services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_access
      - api_access
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    ports:
      - 3001:3001
    networks:
      - app_access
      - api_access
      - db_access
  database:
    container_name: database
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_HOST: host
      POSTGRES_PORT: port
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    ports:
      - 5432:5432
    networks:
      - api_access
      - db_access
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: 
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - "5050:5050"
    networks:
      - db_access
networks:
  app_access:
    driver: bridge
  api_access:
    driver: bridge
  db_access:
    driver: bridge
