services:
  web:
    container_name: web
    build:
      context: ../apps/web/
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_access
      - api_access
  api:
    container_name: api
    build:
      context: ../apps/api/
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3001:3001
    networks:
      - app_access
      - api_access
      - db_access
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_URL=${DATABASE_URL}
  log:
    container_name: log
    image: datalust/seq
    restart: unless-stopped
    ports:
      - 10080:80
      - 15341:5341
    volumes:
      - logdata:/var/lib/seq/data
    environment:
      ACCEPT_EULA: "Y"
    networks:
      - api_access
  database:
    container_name: database
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 15432:5432
    healthcheck:
      # specifying user and database is needed to avoid `FATAL:  role "root" does not exist`
      # spam in the logs
      test: ['CMD', 'pg_isready', '-U', 'prisma', '-d', 'tests']
      interval: 5s
      timeout: 2s
      retries: 20
    networks:
      - api_access
      - db_access
  objstorage:
    container_name: objstorage
    image: bitnami/minio:latest
    ports:
      - 19000:9000
      - 19001:9001
    volumes:
      - objstorage:/var/lib/minio/data
    networks:
      - api_access
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT=${PGADMIN_PORT}
    ports:
      - "15050:5050"
    networks:
      - db_access
networks:
  app_access:
    driver: bridge
  api_access:
    driver: bridge
  db_access:
    driver: bridge
