services:
  database:
    container_name: database
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=dokhub
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    healthcheck:
      # specifying user and database is needed to avoid `FATAL:  role "root" does not exist`
      # spam in the logs
      test: ['CMD', 'pg_isready', '-U', 'prisma', '-d', 'tests']
      interval: 5s
      timeout: 2s
      retries: 20
  vectorstore:
    container_name: vectorstore
    image: qdrant/qdrant:latest
    restart: always
    volumes:
      - vectordata:/var/lib/qdrant/data
    ports:
      - 6333:6333
      - 6334:6334
  objstorage:
    container_name: objstorage
    image: quay.io/minio/minio:latest
    restart: always
    volumes:
      - ~/minio/data:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    ports:
      - 9000:9000
      - 9001:9001
    command: server --console-address ":9001" /data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  dbdata:
  vectordata:
